name: Build & Deploy spring app
on:
  push:
  branch:
    -master

jobs:
  build-deploy:
    name: Build &Deploy spring app
    runs-on: ubuntu-latest

    steps:
     - name: checkout code
       uses: actions/checkout@v3

     - name: Setup JDK 17
       uses: actions/setup-java@v3
       with:
         distribution: 'corretto'
         java-version: '17'

     - name: Unit Tests
       run: mvn -B test --file pom.xml

     - name: build package
       run: |
               mvn clean
               mvn -B test --file pom.xml
               
           


             
             

